### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Keno** [JuliaComputing/ArrayFire.jl#2]
Things I have done so far since my update on the list:
- Fix arrayfire's build system to work well for us
- Integrate the subarray mechanism (this turned out to be be a lot easier than expected, but the build system turned out harder, so it balances out)
- A few more library wrappers

At this point we can run the example in arrayfire's README without any trouble.

Things to do:
- [ ] Figure out binary distribution (ask me if you need help, it's tricky)
- [ ] Wrap the remaining ArrayFire functionality
- [ ] Examples
- [ ] Documentation
- [ ] Testing

Things to do for me:
- [x] Fix memory management - Currently it's leaking GPU memory - Should be simple
- [x] Exceptions

**Comment by ViralBShah** [comment]
Closing this, as we are mostly doing many of these things already, and specific issues are needed from now on.
